[package]
name = "speleodb-compass-sidecar-ui"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
console_error_panic_hook = "0.1.7"
getrandom = {version = "0.3.4", features = ["wasm_js"] }
gloo-timers = { version = "0.3.0", features = ["futures"] }
futures = "0.3"
js-sys = "0.3"
log = "0.4"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-wasm-bindgen = "0.6"
thiserror = "2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
web-sys = { version = "0.3", features = ["HtmlSelectElement"] }
yew = { version = "0.21", features = ["csr"] }

speleodb_compass_common = { path = "common" }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[workspace]
members = ["src-tauri", "common"]
